hakam_multi_tenancy:
  tenant_database_className: App\Entity\Main\TenantDbConfig
  tenant_database_identifier: id
  tenant_connection:
    host: 127.0.0.1
    driver: pdo_pgsql
    charset: utf8
  tenant_migration:
    tenant_migration_namespace: DoctrineMigrations\Tenant
    tenant_migration_path: migrations/Tenant
  tenant_entity_manager:
    mapping:
      type: attribute
      dir: '%kernel.project_dir%/src/Entity/Tenant'
      prefix: App\Entity\Tenant
      alias: Tenant

doctrine:
  orm:
    mappings:
      App:
        is_bundle: false
        type: attribute
        dir: '%kernel.project_dir%/src/Entity/Main'
        prefix: App\Entity\Main
        alias: App

doctrine_migrations:
  migrations_paths:
    DoctrineMigrations: '%kernel.project_dir%/migrations/Main'
